version: "3.9"

networks:
  couch:
    driver: overlay
    attachable: true

services:
  nginx:
    image: comp90024/nginx_wrapper
    build: ./nginx
    ports:
      - 5984:5984
      - 6984:6984
      - 80:80
      - 443:443
    networks:
      couch:
  
  api:
    image: comp90024/api
    build: ./api
    environment:
      - COUCHDB_USER={{couchdb_username}}
      - COUCHDB_PASSWORD={{couchdb_password}}
      - COUCHDB_HOST=nginx.
    networks:
      couch:

  couch1:
    image: comp90024/couch_wrapper
    build: ./couch
    environment:
      - COUCHDB_USER={{couchdb_username}}
      - COUCHDB_PASSWORD={{couchdb_password}}
      - COUCHDB_SECRET={{couchdb_secret}}
      - ERL_FLAGS=-setcookie "{{couchdb_secret}}" -name couchdb@couch1. -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9200
      - NODENAME=couch1.
    networks:
      couch:

  couch2:
    image: comp90024/couch_wrapper
    build: ./couch
    environment:
      - COUCHDB_USER={{couchdb_username}}
      - COUCHDB_PASSWORD={{couchdb_password}}
      - COUCHDB_SECRET={{couchdb_secret}}
      - ERL_FLAGS=-setcookie "{{couchdb_secret}}" -name couchdb@couch2. -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9200
      - NODENAME=couch2.
    networks:
      couch:

  couch3:
    image: comp90024/couch_wrapper
    build: ./couch
    environment:
      - COUCHDB_USER={{couchdb_username}}
      - COUCHDB_PASSWORD={{couchdb_password}}
      - COUCHDB_SECRET={{couchdb_secret}}
      - ERL_FLAGS=-setcookie "{{couchdb_secret}}" -name couchdb@couch3. -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9200
      - NODENAME=couch3.
    networks:
      couch:

# Theoretically, this should do the same thing as in the Dockerfile, but without the need to build a new image
# Doesn't seem to work though...
# configs:
#   couch_config:
#     file: ./couch_config.ini