version: "3.9"

networks:
  couch:
    driver: overlay


services:
  nginx:
    image: alaroldai/comp90024_nginx_wrapper
    build: ./nginx
    ports:
      - 5984:5984
      - 6984:6984

  couch1:
    image: alaroldai/comp90024_couch_wrapper
    build: ./couch
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=answering_railcar
      - COUCHDB_SECRET=a192aeb9904e6590849337933b000c99
      - ERL_FLAGS=-setcookie "a192aeb9904e6590849337933b000c99" -name couchdb@172.17.0.5 -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9200
      - NODENAME=172.17.0.5
    networks:
      couch:
        aliases:
          - 172.17.0.5

    couch2:
    image: alaroldai/comp90024_couch_wrapper
    build: ./couch
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=answering_railcar
      - COUCHDB_SECRET=a192aeb9904e6590849337933b000c99
      - ERL_FLAGS=-setcookie "a192aeb9904e6590849337933b000c99" -name couchdb@172.17.0.6 -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9200
      - NODENAME=172.17.0.6
    networks:
      couch:
        aliases:
          - 172.17.0.6

    couch3:
    image: alaroldai/comp90024_couch_wrapper
    build: ./couch
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=answering_railcar
      - COUCHDB_SECRET=a192aeb9904e6590849337933b000c99
      - ERL_FLAGS=-setcookie "a192aeb9904e6590849337933b000c99" -name couchdb@172.17.0.7 -kernel inet_dist_listen_min 9100 -kernel inet_dist_listen_max 9200
      - NODENAME=172.17.0.57
    networks:
      couch:
        aliases:
          - 172.17.0.7

# Theoretically, this should do the same thing as in the Dockerfile, but without the need to build a new image
# Doesn't seem to work though...
# configs:
#   couch_config:
#     file: ./couch_config.ini