# Run using `openstack --os-cloud nectar-private stack create -t test.yml test --parameter key_name=alaroldai_haliax`
# See also: https://github.com/NeCTAR-RC/heat-templates/blob/master/basic_server.yaml
---
heat_template_version: 2018-08-31
description: >
  A simple deployment of two VMs on Nectar
  Stores the ip addresses of the servers in 

parameters:
  key_name:
    type: string
    description: Keypair for SSH access
    constraints:
      - custom_constraint: nova.keypair
        description: Must be an existing keypair

  flavor:
    type: string
    description: Flavor
    default: t3.xsmall
    constraints:
      - custom_constraint: nova.flavor
        description: Must be an existing flavor

  image:
    type: string
    description: Image ID or name
    default: NeCTAR Debian 10 (Buster) amd64

  # availability_zone:
  #   type: string
  #   description: Availability Zone


resources:
  ssh_secgroup:
    # https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Neutron::SecurityGroup
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
  docker_swarm_secgroup:
    # https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 2377
          port_range_max: 2377
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 7946
          port_range_max: 7946
        - remote_ip_prefix: 0.0.0.0/0
          protocol: udp
          port_range_min: 7946
          port_range_max: 7946
        - remote_ip_prefix: 0.0.0.0/0
          protocol: udp
          port_range_min: 4789
          port_range_max: 4789

  manager:
    # https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Nova::Server
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      tags: ['docker-manager']
      # availability_zone: { get_param: availability_zone }
      security_groups:
      - { get_resource: ssh_secgroup }
      - { get_resource: docker_swarm_secgroup }
      networks:
        - allocate_network: auto

  worker:
    # https://docs.openstack.org/heat/latest/template_guide/openstack.html#OS::Nova::Server
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      tags: ['docker-worker']
      # availability_zone: { get_param: availability_zone }
      security_groups:
      - { get_resource: ssh_secgroup }
      - { get_resource: docker_swarm_secgroup }
      networks:
        - allocate_network: auto

outputs:
  manager_ip:
    description: The IP address of manager node
    value: { get_attr: [manager, first_address] }
  worker_ip:
    description: The IP address of worker node
    value: { get_attr: [worker, first_address] }
